/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bp2project;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class books extends javax.swing.JFrame {

    /**
     * Creates new form books
     */
    public books() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nprice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bkname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        ret = ret = new RoundButton(" ");
        sell = sell = new RoundButton(" ");
        update = update = new RoundButton(" ");
        update1 = update1 = new RoundButton(" ");
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        book = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        price = new javax.swing.JTextField();

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1081, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("NEW BOOK");

        nprice.setBackground(new java.awt.Color(204, 204, 204));
        nprice.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nprice.setText("Price");
        nprice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                npriceMouseClicked(evt);
            }
        });
        nprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npriceActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAME", "PRICE"
            }
        ));
        jScrollPane1.setViewportView(table);

        bkname.setBackground(new java.awt.Color(204, 204, 204));
        bkname.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        bkname.setText("Name");
        bkname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bknameMouseClicked(evt);
            }
        });
        bkname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bknameActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("GET FROM TEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(512, 512, 512))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(nprice, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(bkname, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(74, 74, 74)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(478, 478, 478)
                                .addComponent(jButton3))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bkname, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nprice, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ADD", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));

        ret.setText("RETURN");
        ret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retActionPerformed(evt);
            }
        });

        sell.setText("SELL");
        sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellActionPerformed(evt);
            }
        });

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        update1.setText("GO BACK");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ret, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(sell, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(ret, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(update1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("GENERAL INFO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));

        book.setBackground(new java.awt.Color(204, 204, 204));
        book.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        book.setText("Book");
        book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookMouseClicked(evt);
            }
        });
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "BOOK", "PRICE", "TIME"
            }
        ));
        jScrollPane2.setViewportView(Table);

        price.setBackground(new java.awt.Color(204, 204, 204));
        price.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        price.setText("Price");
        price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priceMouseClicked(evt);
            }
        });
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(373, 373, 373))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 525, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("SELL", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseClicked
        //set null string
        book.setText("");
    }//GEN-LAST:event_bookMouseClicked
int i = 0;
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        //refresh data from mysql using select
        DefaultTableModel rr = (DefaultTableModel) Table.getModel();
        rr.setRowCount(0);
        if(i>=0){
            Table.removeAll();

        }
        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from  selled");

            while (rs.next()) {
                String r1 = rs.getString("id");
                String r2 = rs.getString("book");
                String r3 = rs.getString("price");
                String r4 = rs.getString("Time");
                Object[] rw = {r1, r2, r3, r4 };

                rr.addRow(rw);

            }

        }catch (Exception e) {
            System.out.println(e.getMessage());
        }
        i++;

    }//GEN-LAST:event_updateActionPerformed

    private void sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellActionPerformed
        // get todays time and chek input with regex after isert this data in mysql 
        int yeni = 0;
        int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure? "); 
        if(a==JOptionPane.YES_OPTION){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        PreparedStatement ps = null;
        DefaultTableModel rr = (DefaultTableModel) Table.getModel();
        rr.setRowCount(0);
        String regex = ".*[A-Za-z].*[A-Za-z].*[A-Za-z].*";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(book.getText());

        boolean result = matcher.matches();
        if(result == true){
            try{
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
                String rs=("insert into selled(book, Price, Time) values  (?,?,?) ");
                ps = con.prepareStatement(rs);
                ps.setString(1, book.getText());
                ps.setString(2, price.getText());
                ps.setString(3,sdf.format(new Date()) );
                boolean i = ps.execute();
                System.out.println("Record updated successfully.");
            }catch (Exception e) {
                System.out.println(e.getMessage());
            }

        }else if(result == false){
            JOptionPane.showMessageDialog(this, "Book can't be a null " );
        }
       }
      PreparedStatement oc = null;
       PreparedStatement op = null; 
      try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
            String rc=("delete from new where book = ? ");
            oc = con.prepareStatement(rc);
            oc.setObject(1, book.getText() );
            oc.executeUpdate();
            //System.out.println("Record updated successfully.");
        }catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Price can't contain any character ");
        }   
          try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
            Statement stmnt=conn.createStatement();
            ResultSet ro=stmnt.executeQuery("select * from  cash");

            while (ro.next()) {
                yeni = ro.getInt("cash");
            }
           
            String rm=("delete  from cash ");
            op = conn.prepareStatement(rm);
            int i = op.executeUpdate();
        }catch (Exception e) {
            System.out.println(e.getMessage());
        }
          yeni +=Integer.parseInt(price.getText());
          
       PreparedStatement ne = null;
          try{
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
                String rs=("insert into cash(cash) values(?) ");
                ne = con.prepareStatement(rs);
                ne.setInt(1, yeni);
                
             
                boolean i = ne.execute();
                System.out.println("Record updated successfully.");
            }catch (Exception e) {
                System.out.println(e.getMessage());
            }   
    }//GEN-LAST:event_sellActionPerformed

    private void retActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retActionPerformed
        // get book back  
        int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure?"); 
       if(a==JOptionPane.YES_OPTION){
        
        PreparedStatement oc = null;
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
            String rc=("delete from selled where id = ? ");
            oc = con.prepareStatement(rc);
            oc.setObject(1, Table.getValueAt(Table.getSelectedRow(), 0));
            oc.executeUpdate();
            System.out.println("Record updated successfully.");
        }catch (Exception e) {
            System.out.println(e.getMessage());
        }
       
       int yeni=0;
       PreparedStatement ps = null;
       PreparedStatement op = null;
       try{
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
                String rs=("insert into new(book, price) values  (?,?) ");
                ps = con.prepareStatement(rs);
                ps.setString(1, (String) Table.getValueAt(Table.getSelectedRow(), 1));
                ps.setString(2, (String) Table.getValueAt(Table.getSelectedRow(), 2));
                
                boolean i = ps.execute();
                System.out.println("Record updated successfully.");
            }catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Price can't contain any character ");
            }
           
            try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
            Statement stmnt=conn.createStatement();
            ResultSet ro=stmnt.executeQuery("select * from  cash");

            while (ro.next()) {
                yeni = ro.getInt("cash");
            }
           
            String rm=("delete  from cash ");
            op = conn.prepareStatement(rm);
            int i = op.executeUpdate();
        }catch (Exception e) {
            System.out.println(e.getMessage());
        }
          yeni -=Integer.parseInt((String) Table.getValueAt(Table.getSelectedRow(), 2));
          
       PreparedStatement ne = null;
          try{
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
                String rs=("insert into cash(cash) values(?) ");
                ne = con.prepareStatement(rs);
                ne.setInt(1, yeni);
                
             
                boolean i = ne.execute();
                System.out.println("Record updated successfully.");
            }catch (Exception e) {
                System.out.println(e.getMessage());
            }
       }
    }//GEN-LAST:event_retActionPerformed

    private void npriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_npriceMouseClicked
      nprice.setText(" ");
    }//GEN-LAST:event_npriceMouseClicked

    private void bknameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bknameMouseClicked
        bkname.setText(" ");
    }//GEN-LAST:event_bknameMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // refresh books in 2 table
        DefaultTableModel tbl = (DefaultTableModel) table.getModel();
        tbl.setRowCount(0);
        if(i>=0){
            table.removeAll();

        }
        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from  new");

            while (rs.next()) {
                String rn = rs.getString("book");
                
                String rb = rs.getString("price");
                
                Object[] tw = {rn, rb };

                tbl.addRow(tw);

            }

        }catch (Exception e) {
            System.out.println(e.getMessage());
        }
        i++;
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //add new books in system
        PreparedStatement ps = null;
        DefaultTableModel rr = (DefaultTableModel) Table.getModel();
        rr.setRowCount(0);
        
        String uregex = ".*[A-Za-z].*[A-Za-z].*[A-Za-z].*";
        Pattern upattern = Pattern.compile(uregex);
        Matcher umatcher = upattern.matcher(bkname.getText());
        boolean uresult = umatcher.matches();
       
        if(uresult== true){
            try{
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
                String rs=("insert into new(book, price) values  (?,?) ");
                ps = con.prepareStatement(rs);
                ps.setString(1, bkname.getText());
                ps.setString(2, nprice.getText());
                
                boolean i = ps.execute();
                System.out.println("Record updated successfully.");
            }catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Price can't contain any character ");
            }

        }else if(uresult == false){
            JOptionPane.showMessageDialog(this, "Name can't be a null " );
        }
        DefaultTableModel tbl = (DefaultTableModel) table.getModel();
        tbl.setRowCount(0);
        if(i>=0){
            table.removeAll();

        }
        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from  new");

            while (rs.next()) {
                String rn = rs.getString("book");
                
                String rb = rs.getString("price");
                
                Object[] tw = {rn, rb };

                tbl.addRow(tw);

            }

        }catch (Exception e) {
            System.out.println(e.getMessage());
        }
        i++;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //delete book in system
        int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure?"); 
       if(a==JOptionPane.YES_OPTION){
        PreparedStatement ps = null;
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
            String rs=("delete from new where book = ? ");
            ps = con.prepareStatement(rs);
            ps.setObject(1, table.getValueAt(table.getSelectedRow(), table.getSelectedColumn()) );
            int i = ps.executeUpdate();
            System.out.println("Record updated successfully.");
        }catch (Exception e) {
            System.out.println(e.getMessage());
        }
        PreparedStatement oc = null;
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
            String rc=("delete from new where price= ? ");
            oc = con.prepareStatement(rc);
            oc.setObject(1, table.getValueAt(table.getSelectedRow(), table.getSelectedColumn()) );
            oc.executeUpdate();
            //System.out.println("Record updated successfully.");
        }catch (Exception e) {
            System.out.println(e.getMessage());
           
        }
       }
       DefaultTableModel tbl = (DefaultTableModel) table.getModel();
        tbl.setRowCount(0);
        if(i>=0){
            table.removeAll();

        }
        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from  new");

            while (rs.next()) {
                String rn = rs.getString("book");
                
                String rb = rs.getString("price");
                
                Object[] tw = {rn, rb };

                tbl.addRow(tw);

            }

        }catch (Exception e) {
            System.out.println(e.getMessage());
        }
        i++;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        // Get an another frame
        int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure?"); 
       if(a==JOptionPane.YES_OPTION){
        Menu b = new Menu();
       b.show();
       dispose();}
    }//GEN-LAST:event_update1ActionPerformed
 String[] data = new String[3];
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      //open txt file and insert data in database
     
JFileChooser chooser = new JFileChooser();
FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
chooser.setFileFilter(filter);

int returnVal = chooser.showOpenDialog(null);
if (returnVal == JFileChooser.APPROVE_OPTION) {
    File file = chooser.getSelectedFile();
    try (Scanner reader = new Scanner(file);
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004")) {
        while (reader.hasNextLine()) {
            // Split the current line by comma
            String line = reader.nextLine();
            data = line.split(",");
            System.out.println(data.length);
            // Make sure we have at least two columns
            if (data.length < 2) {
                continue;
            }
            // Prepare and execute the INSERT statement for each line
            String sql = "INSERT INTO new(book, price) VALUES (?, ?)";
            try (PreparedStatement ps = con.prepareStatement(sql)) {
                ps.setString(1, data[0]);
                ps.setString(2, data[1]);
                int rowsAffected = ps.executeUpdate();
                
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    DefaultTableModel tbl = (DefaultTableModel) table.getModel();
        tbl.setRowCount(0);
        if(i>=0){
            table.removeAll();

        }
        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/people","root","26052004");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from  new");

            while (rs.next()) {
                String rn = rs.getString("book");
                
                String rb = rs.getString("price");
                
                Object[] tw = {rn, rb };

                tbl.addRow(tw);

            }

        }catch (Exception e) {
            System.out.println(e.getMessage());
        }
        i++;
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void priceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priceMouseClicked
       price.setText("");
    }//GEN-LAST:event_priceMouseClicked

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookActionPerformed

    private void bknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bknameActionPerformed
        bkname.setText("");
    }//GEN-LAST:event_bknameActionPerformed

    private void npriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npriceActionPerformed
nprice.setText("");      
    }//GEN-LAST:event_npriceActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextField bkname;
    private javax.swing.JTextField book;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nprice;
    private javax.swing.JTextField price;
    private javax.swing.JButton ret;
    private javax.swing.JButton sell;
    private javax.swing.JTable table;
    private javax.swing.JButton update;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
